### PR TITLE
Ignore mention in `telegrinder.rules.Command`

### PR DESCRIPTION
**Pull request by prostomarkeloff**
### ✏️ Description ✏️
This feature lets a bot work in groups, cause inthere commands sent to a bot must be in a format like `/cmd@bot_username`. So, this little PR just always removes a mention if there is and lets a bot work in group chats.

### 📍 Type of change 📍
- [x] 🚀 New feature (non-breaking change which adds functionality) 🚀

### ⚪️ Checklist ⚪️
* [x] 📝 Your code has documentation 📝
* [] 🔧 Your code has tests 🔧
* [] 🪄 Your code has example usage in `/examples` 🪄

### CODE REVIEW

**Comment by prostomarkeloff** [comment]
With the extra commit the PR introduces the possibility to validate the mention. If the bot is asked at a group it'll check if the mention with which it's asked is truly its.

**Comment by vffuunnyy** [comment]
maybe

```python
def cut_mention(text: str) -> tuple[str, str | None]:
    try:
        prefix, mention = text.split("@", 1)
        return prefix, mention
    except ValueError:
        return text, None
```

**Comment by prostomarkeloff** [comment]
lgtm, i'll let @timoniq decide what is better

**Comment by timoniq** [comment]
I think it may be better moving this logic to an independent command node that will contain information including mention

**Pull request merged**
